name: 'Ritchie CLI action (java 8)'

description: 'Execute Ritchie CLI formulas implemented in JAVA 8'

inputs:
  rit-repo-url:
    description: 'Ritchie repository'
    required: true
    default: 'https://github.com/ZupIT/ritchie-formulas-demo'
  rit-formula-command:
    description: 'Ritchie formula command with input flags'
    required: true
    default: 'rit --version'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.rit-repo-url }}
    - ${{ inputs.rit-formula-command }}

branding:
  icon: "settings"
  color: "orange"
